version: "3"

services:
    db:
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
        networks:
            - wp
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - '8080:80'
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: password
        networks:
            - wp

    wordpress:
        depends_on:
            - db
        image: wordpress:latest
        ports:
           - '5000:80'
        restart: always
        volumes: ['./:/var/www/html']
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
        networks:
            - wp

    vue:
        build:
            context: .
            dockerfile: Dockerfiles/vue.dockerfile
        depends_on:
            - db
        networks:
            - wp
        volumes: ['./vue-front:/app']
        ports:
            - '8200:8200'
networks:
    wp:
volumes:
    db_data:
